# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=31)),
                ('sex', models.CharField(default='1', max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'T_USER',
                'ordering': ['create_date'],
            },
        ),
    ]
